### ISSUE TITLE
Create a fetcher (3)

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#1]
Have the fetcher pull lines from viz.yaml that includes all of the analytics IDs.

**Comment by eread-usgs** [comment]
- [ ] refer to figures/ report components to determine data requirements.

**Comment by eread-usgs** [comment]
data requirements now described @wdwatkins

**Comment by wdwatkins** [comment]
viewID is what we want to use to reference apps

**Comment by wdwatkins** [comment]
probably want to run this fetcher twice, since there will be two GA accounts with different credentials
