### ISSUE TITLE
add WIM accounts to analytics page

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#105]
Long Names:
1. USGS Flood Event Viewer
2. Flood Innundation Mapper
3. USGS Ground Water Watch
4. Mississippi River Basin Flood of 2015/2016
5. National Water-Quality Assessment - Decadal Trends Mapper
6. National Water-Quality Assessment - Water Quality Changes in the Nation's Streams and Rivers
7. National Water Information System Mapper
8. National Water Information System Mapper - Water Alert
9. USGS StreamStats
     10. Connection River Systems Restoration Assessment Web App
     11. Saginaw Bay Restoration Assessment Web App
     12. Western Lake Erie Restoration Assessment Web App
13. NPS Mercury Mapper
14. Sparrow Tennessee

Short Names:
1. FEV
2. FIM
3. GroundWaterWatch
4. MARB
5. NaWQADecadalTrendsMapper
6. NaWQASWTrends
7. NWISMapper
8. NWISMapper-WaterAlert
9. StreamStats
     10. GLCWRA-CRSRA
     11. GLCWRA-SBRA
     12. GLCWRA-WLERA
13. NPSMercuryMapper
14. Sparrow Tennessee

**Comment by eread-usgs** [comment]
@wdwatkins if you want me to add these to that google sheet, i'd be happy to (or let me know what I can do to assist getting these into the app).

**Comment by wdwatkins** [comment]
@eread-usgs the account info is stored here: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/ga_table.csv.  You just need to fill in the long/short names, URL, and viewID, the other columns aren't being used.

**Comment by wdwatkins** [comment]
GroundWaterWatch, is already there, I am working on the rest.  I noticed that the NAWQA SW trends view lists a test url in the `websiteUrl` field, although this is just whatever they entered into the UI, not necessarily where the data comes from.  Might be worth checking though?

**Comment by wdwatkins** [comment]
@eread-usgs these are all added now, they just need description fields filled in.
