### ISSUE TITLE
add WMA static content UAs

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#106]
@wdwatkins please see the emails from me and Howard Perlman on May 3 for add'l details. Include 'Not W.S. School' and 'Water Science School' views as a start. Short/long names for these two should be:

View / Short name / long name
'Not W.S. School' / water.usgs.gov / water.usgs.gov
'Water Science School' / WaterSciSchool / Water Science School

**Comment by wdwatkins** [comment]
@eread-usgs Those two are added, are there any others?
