### ISSUE TITLE
add in short description of each application at the top of the page. 

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#107]

**Comment by eread-usgs** [comment]
@lindsaycarr or @wdwatkins can one of you take this on over the next week or two? We need to add project descriptions and contact info for applications included in the analytics report (see attachment). Here (https://docs.google.com/spreadsheets/d/1NEpyAPCdQUvFUHl7AKAXE1UDB-aEq51Ni5mn2-EdkFY/edit#gid=1262354658) I have compiled a brief description of a number of these applications, but not all. Contact /leads are also shown. 

Most OWI apps are shown there, but for those that are not OWI apps, we need to create a 1-2 sentence description. I put the summaries together for OWI apps fairly easily by pulling text from the 'about' page. I don't think it would take more than an hour to gather or create summaries for remaining apps. 

In terms of contacts for the non-OWI apps, see if you can also pull that from the 'About' pages that most apps have. We can deal w edge cases as they arise...

The second question that is still open is where/how we'll get the application description text into the app. @wdwatkins  do you recall where we left off on that?

related to #101 


![screen shot 2017-06-09 at 3 53 43 pm](https://user-images.githubusercontent.com/7794368/26994141-f3c161a0-4d2b-11e7-91e5-c78552f98436.png)

**Comment by lindsaycarr** [comment]
I can take this on next week!

**Comment by eread-usgs** [comment]
thanks @lindsaycarr, and let me know if you have questions once you get going on it.

**Comment by wdwatkins** [comment]
@lindsaycarr There is a field in the app yaml file: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/gaTable.yaml#L13

**Comment by lindsaycarr** [comment]
@eread-usgs how long should these descriptions be? One sentence, a paragraph, or two paragraphs?

**Comment by lindsaycarr** [comment]
Nevermind - found your descriptions (forgot you had them already)

**Comment by lindsaycarr** [comment]
Still need:

- [ ] Great Lakes Restoration Initiative Phragmites
- [ ] Biodata Retrieval

**Comment by lindsaycarr** [comment]
@eread-usgs what do I need to do for the ones with `.na.character` in their description? That starts with `water.usgs.gov` and ends with `Flood Inundation Mapper`. Then, the last two `USGS Flood Event Viewer` and `National Water Information System Mapper` have `"NA"`.

**Comment by lindsaycarr** [comment]
Still need to get b/c they don't have working URLs listed.

- [ ] Streamer - TX WSC
- [ ] SparrowTN
- [ ] Flood Inundation Mapper

**Comment by lindsaycarr** [comment]
Need to add contacts to each app:

- Project Contact
- Analytics Contact

**Comment by lindsaycarr** [comment]
Some applications seem like they don't have an owner, so I put @eread-usgs for now.

- CIDA Website
- VizLab: California Drought
- VizLab: Colorado River Drought
- OWI Website
- water.usgs.gov

Also, I put Gary Latzke for anything related to WIM.

- StreamStats
- SparrowTN
- NaWQASWTrends
- NaWQADecadalTrendsMapper
- NPSMercuryMapper
- MARB
- GLCWRA-WLERA
- GLCWRA-SBRA
- GLCWRA-CRSRA
- FIM
- FEV

**Comment by eread-usgs** [comment]
thanks @lindsaycarr !!
