### ISSUE TITLE
Template and layout for pages

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#14]
per the mock ups below + header + footer
![img_20170329_103907](https://cloud.githubusercontent.com/assets/7794368/24478227/ac0c6e1e-149f-11e7-93d7-4f566e311f0a.jpg)
![img_20170329_103859](https://cloud.githubusercontent.com/assets/7794368/24478234/b54f8b00-149f-11e7-9dd2-62124439b45f.jpg)

**Comment by eread-usgs** [comment]
@mwernimont I know you may not have context for this yet- I'll fill you in the next time I see you.

**Comment by eread-usgs** [comment]
Consider using twitter bootstrap for this? Need some way to control layout. Lets discuss @mwernimont

**Comment by mwernimont** [comment]
I don't really know what is going on, but my 2 cents is I'd rather use flexbox than bootstrap. I think I kinda see what you want, and flexbox is pretty flexible.

**Comment by jiwalker-usgs** [comment]
I defer to you on this one, I just think it is probably be good to go a bit more in on a framework for this viz.

**Comment by eread-usgs** [comment]
I think this is complete with https://github.com/USGS-VIZLAB/internal-analytics/pull/27
