### ISSUE TITLE
display a 0 when there isn't any traffic for a time period on figure 1

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/internal-analytics#151]
Instead of empty lines:
![image](https://user-images.githubusercontent.com/2349007/27961090-32d9099c-62f3-11e7-92a9-ea2f948715b1.png)

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/28040727-530391d8-658c-11e7-87bd-7a0a1b8ee399.png)

Does that look OK @jread-usgs ?
