### ISSUE TITLE
Create skeleton for the pages

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#16]
- [x]  summary 'home' page and ~20 pages per application
- [x] dev job deployed

**Comment by eread-usgs** [comment]
@jiwalker-usgs , this is a friendly reminder that we planned for this to be complete before monday at 10am.

**Comment by eread-usgs** [comment]
waiting on https://github.com/USGS-VIZLAB/internal-analytics/issues/14 to be complete

**Comment by jiwalker-usgs** [comment]
I'm going to hand this to @mwernimont as his next PR should handle this.

**Comment by eread-usgs** [comment]
@jiwalker-usgs should this be closed with https://github.com/USGS-VIZLAB/internal-analytics/pull/27?  Not sure things are up on Dev yet, which is one of the check boxes above....
