### ISSUE TITLE
Get fetcher to only pull most recent data and a couple misc items

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#19]
- [x] see comments here: https://github.com/USGS-VIZLAB/internal-analytics/pull/18

- [x] Did lindsay do something for github create repo that could be used as a pattern for authenticating twice with Jenkins. Dont push this up to github.

- [x] By end of the day, get the fetcher running so data are on SB. 

- [x] using chunking to get all the data

**Comment by eread-usgs** [comment]
Need to discuss options for this at the retro.

**Comment by wdwatkins** [comment]
We are set now, unless new things come up.

**Comment by eread-usgs** [comment]
yes!  nice work @wdwatkins
