### ISSUE TITLE
partial data not working for non-year calcs?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/internal-analytics#193]
WMA internal wiki was added and has a partial month:
![image](https://user-images.githubusercontent.com/2349007/28530662-2eae8968-705a-11e7-9583-8cb29e861f10.png)
but the marker style for month makes it look like it has at least 90% data coverage for that time period:
![image](https://user-images.githubusercontent.com/2349007/28530685-4626c632-705a-11e7-898a-456cd5ac1475.png)

**Comment by aappling-usgs** [comment]
ah ha! `process.fill_missing` was assigning the same date range (`n_actual`) to all viewIDs. just need a `group_by()` in there so that ranges are computed for each viewID separately.

**Comment by jread-usgs** [comment]
Good find!

**Comment by aappling-usgs** [comment]
yep, that did it.

from:
![image](https://user-images.githubusercontent.com/12039957/28537857-275efdb2-7061-11e7-8fb4-5a077bbdf335.png)

to:
![image](https://user-images.githubusercontent.com/12039957/28539216-c6a7cb7a-7065-11e7-9a8b-be2452677ddf.png)
