### ISSUE TITLE
Master table of analytics ID, Long name, short names, and URL

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#2]

**Comment by eread-usgs** [comment]
@wdwatkins if you get this started coming at it from the analytics side of things, I can work it from the other end, in terms of long and short names that jive with our and our partners' expectations/naming schemes.

**Comment by eread-usgs** [comment]
Put it in the repo

**Comment by wdwatkins** [comment]
@eread-usgs https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/cida_ga_table.csv

**Comment by eread-usgs** [comment]
Thanks @wdwatkins. Did you notice that 'bot filtering enabled' is TRUE only on 5 projects? Any implications for our work @wdwatkins @jiwalker-usgs @jread-usgs

**Comment by wdwatkins** [comment]
most traffic on dataRetrieval github.io is bots:
![image](https://cloud.githubusercontent.com/assets/13987349/24762339/af9737de-1ab3-11e7-9e1b-9f5e91962c1a.png)

**Comment by wdwatkins** [comment]
Got down a bit of a rabbit hole with this, but my impression is that on heavily-used apps we can get away with ignoring bots, but with less traffic they start really skewing things.

**Comment by eread-usgs** [comment]
@wdwatkins , we now have a  google sheet (https://docs.google.com/spreadsheets/d/1qxFsMfHU3DsLuxT-zvq6WORwM2-Ga3HqWPdQcElMp3s/edit#gid=1693340031) that is commented out and has some new rows but which are incomplete in terms of IDs, etc. Please use Column N to determine which accounts we should include, and note the two new ones at the bottom that also need to be added. Let me know if you have questions.
