### ISSUE TITLE
"Last updated" Stamp

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#33]
What time of day should we update the analytics- midnight?

We should show at the top of the page when it was last updated....

**Comment by eread-usgs** [comment]
@mwernimont want to think about a good location from design perspective to add a timestamp?

**Comment by wdwatkins** [comment]
midnight/early morning would make the most sense I think - I have set up the fetcher to download up through the previous full day's data to simply appending the latest new data.
