### ISSUE TITLE
Portfolio summary Session bar chart

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#4]
Mock it up.

**Comment by eread-usgs** [comment]
- [ ] Title
- [ ] Legend
- [ ] Axis labels

**Comment by eread-usgs** [comment]
![screen shot 2017-03-29 at 4 44 31 pm](https://cloud.githubusercontent.com/assets/7794368/24478049/0202f942-149f-11e7-857e-dafed6be049f.png)

**Comment by ldecicco-USGS** [comment]
I'll start a "portfolio" graph now to make sure it's as easy as the "application" pages.
