### ISSUE TITLE
Map - fixing it up

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#48]
- [ ]  Make colors grayscale 
- [x] Legend title should read sessions
- [ ] Make legend smaller
- [ ] Make Map match in whitespace 
- [x]  Add in Ak and HI
- [ ] Legend gets cut off

**Comment by mwernimont** [comment]
![screen shot 2017-04-24 at 12 08 38 pm](https://cloud.githubusercontent.com/assets/6390096/25349300/ef70a502-28e6-11e7-86fd-ecd17eb78dac.png)
![screen shot 2017-04-24 at 12 08 51 pm](https://cloud.githubusercontent.com/assets/6390096/25349304/f1c45f6a-28e6-11e7-97b3-d0cad1d553f8.png)

**Comment by mwernimont** [comment]
The front page map(top picture) has a weird padding that causes a giant white space between the map and its header. I noticed the details map doesn't have it, are we creating those differently?

**Comment by ldecicco-USGS** [comment]
Yeah, I think @jread-usgs 's last PR fiddled with one map and not the other...I'll have a look.

**Comment by eread-usgs** [comment]
Legend gets cut off in some cases- making it smaller may deal w this issue. 

![screen shot 2017-05-04 at 9 11 10 am](https://cloud.githubusercontent.com/assets/7794368/25707632/bd13a1b6-30a9-11e7-8ffa-c3065694a221.png)
