### ISSUE TITLE
Application report - Sessions: Year/mo/week/day

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#7]

**Comment by eread-usgs** [comment]
- [ ] Title
- [ ] Legend
- [ ] Axis labels

**Comment by eread-usgs** [comment]
![screen shot 2017-03-29 at 4 44 31 pm](https://cloud.githubusercontent.com/assets/7794368/24478049/0202f942-149f-11e7-857e-dafed6be049f.png)

**Comment by ldecicco-USGS** [comment]
@eread-usgs from top to bottom: daily, daily, hourly, hourly?

**Comment by eread-usgs** [comment]
I thought we discussed daily, daily, daily, hourly at our planning mtg 2 weeks ago.... but I'm fine w either @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
I just couldn't remember, daily, daily, daily, hourly it is
