### ISSUE TITLE
create test tier

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#83]

**Comment by jiwalker-usgs** [comment]
I created a new job that will push to http://intcida-test.er.usgs.gov/analytics

**Comment by jiwalker-usgs** [comment]
New job builds nightly (actually 8am) and on merges.  Old job ("prod") only builds nightly.

**Comment by jiwalker-usgs** [comment]
reopened as test site is not quite working yet

**Comment by jiwalker-usgs** [comment]
JIRA issue doesn't seem to be getting much traction, so I'm switching approaches to a different URL

**Comment by jiwalker-usgs** [comment]
Closing this as we have a working test site.
