### ISSUE TITLE
make the big question mark smaller

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#87]
Height of the question mark should be about the same as other figures in the same group.

![screen shot 2017-04-26 at 4 15 58 pm](https://cloud.githubusercontent.com/assets/7794368/25457376/b0960f96-2a9b-11e7-8a14-5730d949ed01.png)

**Comment by mwernimont** [comment]
@jiwalker-usgs is there a way we can add a class to the question mark image so I don't have to do a bunch of CSS work for an image that may or may not appear?

**Comment by ldecicco-USGS** [comment]
I chuckle every time I see the ginormous question mark...are you sure we can't keep it? :smile:

**Comment by jiwalker-usgs** [comment]
I think the easier way would be to change the aspect ratio of the missing.png file.  It is meant as a stand-in for the missing plots, so it should be formatted the same way the plots are.

**Comment by mwernimont** [comment]
so we can just add the aspect ratio thing the charts have in the yaml to the question mark?

**Comment by jiwalker-usgs** [comment]
no, because the question mark is just static from what you gave me
