### ISSUE TITLE
Portfolio sessions- final style touches

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#91]
see attached- each yellow box is a sub task of this issue. 
![screen shot 2017-05-04 at 9 00 25 am](https://cloud.githubusercontent.com/assets/7794368/25707542/81686b7e-30a9-11e7-8a4e-45b34bb7bb8f.png)

**Comment by ldecicco-USGS** [comment]
What does remove outliers mean?

**Comment by eread-usgs** [comment]
remove outlines, not outliers. I mean the black outlines around the boxes.

**Comment by ldecicco-USGS** [comment]
Doh! That sounds much easier.

**Comment by eread-usgs** [comment]
Make legend smaller - legend cuts of data in some cases (see attached)

![screen shot 2017-05-04 at 10 30 59 am](https://cloud.githubusercontent.com/assets/7794368/25711549/d1bb2688-30b4-11e7-9837-c420ddc1bab9.png)
