### ISSUE TITLE
Make pie chart smaller

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/internal-analytics#93]
@mwernimont , could this be made 1/2 of its current size? running into resolution issues b/c we didnt intend it to be so big. 

![screen shot 2017-05-04 at 9 24 44 am](https://cloud.githubusercontent.com/assets/7794368/25708250/942eea10-30ab-11e7-8545-4cc6628d1303.png)

**Comment by mwernimont** [comment]
https://github.com/USGS-VIZLAB/internal-analytics/pull/95
